export const MAX_POKEMON_NUMBER = 905;

export const MOBILE_BREAKPOINT_NUMBER = 480;
export const TABLET_BREAKPOINT_NUMBER = 768;
export const DESKTOP_BREAKPOINT_NUMBER = 1024;
export const LARGE_BREAKPOINT_NUMBER = 1280;